services:
  ethereal-laws-of-mystery:
    image: ethereal-laws-of-mystery:v1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`ethereal-laws-of-mystery.axelerator.de`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
    environment:
      - DATABASE_URL=sqlite:///db-ethereal-laws-of-mystery/db.sqlite
    volumes:
      - /opt/etoml:/opt/etoml
      - /db-ethereal-laws-of-mystery:/db-ethereal-laws-of-mystery



