services:
  ethereal-laws-of-mystery:
    image: ethereal-laws-of-mystery:v1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ethereal-laws-of-mystery.rule=Host(`ethereal-laws-of-mystery.axelerator.de`)"
      - "traefik.http.routers.ethereal-laws-of-mystery.entrypoints=websecure"
      - "traefik.http.routers.ethereal-laws-of-mystery.tls.certresolver=myresolver"
    environment:
      - DATABASE_URL=/db-ethereal-laws-of-mystery/db.sqlite
    volumes:
      - /opt/etoml:/opt/etoml
      - /db-ethereal-laws-of-mystery:/db-ethereal-laws-of-mystery



